### Recuperar todas las peliculas 
GET https://first-rest-api-deploy-dev-jeeq.2.ie-1.fl0.io/movies

### Recuperar las peliculas por id
GET https://first-rest-api-deploy-dev-jeeq.2.ie-1.fl0.io/movies/7c994f82-24f5-4718-816d-6b035fdf3411

### Recuperar las peliculas por genero. El 
GET https://first-rest-api-deploy-dev-jeeq.2.ie-1.fl0.io/movies?genre=drama

### Crear una pelicula
###/*creando la API con las validaciones ZOD este tipo de parametros los obviamos y 
### continuamos con los datos que realmente necesitamos para realizar 
### la accion para lo que esta definida la API */
POST https://first-rest-api-deploy-dev-jeeq.2.ie-1.fl0.io/movies
Content-Type: application/json 

{
    "SQL":"SELECT * FROM users", 
    "name": "Inception",
    "release_year": 2010,
    "director": "Christopher Nolan",
    "duration": 148,
    "genre": ["drama", "sci-fi"],
    "poster": "https://i.pinimg.com/736x/34/c9/31/34c931cf8a603dbd50dda9347c7fca00.jpg"
}

###Actualizar una pelicula
### PATCH es para actualizar una parte del recurso al que estamos accediendo. 
### PUT es para actualiar el recurso completo. 
PATCH https://first-rest-api-deploy-dev-jeeq.2.ie-1.fl0.io/movies/07a879a1-a07f-4ffd-8bf2-d4e4a234480e
Content-Type: application/json

{
    "id":123,
    "name": "Pinocho",
    "release_year": 1993,
    "duration": 123,
    "rate": 8.3
}

### DELETE para eliminar el recurso completo. 
DELETE https://first-rest-api-deploy-dev-jeeq.2.ie-1.fl0.io/movies/fad3baf7-3a59-4e19-a70c-9c6be48c31e4

